
resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
  

- name: flowdock-notification
  type: docker-image
  source:
    repository: starkandwayne/flowdock-notification-resource
    
    
resources:

- name: flowdock-drone
  type: flowdock-notification
  source:
    name: https://api.flowdock.com/messages


- name: snapshots
  type: maven-resource
  source:
    url: http://((nexus_http_host_port))/repository/snapshots
    artifact: com.example:spring-music:jar
    username: admin
    password: admin123

- name: releases
  type: maven-resource
  source:
    url: http://((nexus_http_host_port))/repository/builds
    artifact: com.example:spring-music:jar
    username: admin
    password: admin123


- name: repo
  type: git
  source:
    uri: {{github-repo-uri}}
    branch: ((repo-branch))
    private_key: {{github-private-key}}
  
- name: dev-version
  type: semver
  source:
    driver: git
    uri: {{github-repo-uri}}
    branch: ((repo-version-branch))
    private_key: {{github-private-key}}
    file: version
    initial_version: {{initial-version}}

- name: snap-version
  type: semver
  source:
    driver: git
    uri: {{github-repo-uri}}
    branch: ((repo-version-branch))
    private_key: {{github-private-key}}
    file: snap_version
    initial_version: {{initial-version}}
    
- name: dev-cloud
  type: cf
  source:
    api: {{cf_api}}
    username: {{cf_user}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space}} 
    skip_cert_check: true

jobs:

- name: patch-bump
  serial: true
  serial_groups: [ update_version ]
  plan:
  - get: dev-version  
  - put: dev-version 
    params: { bump: patch }
        
- name: unit
  plan:
  - get: music-repo
    resource: repo
    trigger: true
  - task: unit
    file: music-repo/ci/tasks/unit.yml


  
- name: promote
  serial: true  
  plan:
  - aggregate:
    - get: snapshots
      passed: [build]
    - get: dev-version
      trigger: true      
  - put: releases
    params:
      file: snapshots/spring-music-*.jar
      version_file: dev-version/version  
      
      
- name: build
  serial: true
  plan:
  - aggregate:
    - get: music-repo
      resource: repo
      trigger: true
      passed: [ unit ]
    - get: version  
      resource: snap-version
      
  - task: build
    file: music-repo/ci/tasks/build-artifact.yml
    on_failure:
      put: flowdock-drone
      params:
        text: Build Failed
        thread_title: Building Music
        msg_status_value: FAIL
        msg_title: Build failure
        username: Concourse
        pipeline_name: spring-music
        pipeline_url:  {{nonprod_pipeline_url}}
        statuscolor: cyan
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        flow_token: {{flow_token}}
    on_success:
      put: flowdock-drone
      params:
        text: Build Succeeded
        thread_title: Building Music
        msg_status_value: SUCCESS
        msg_title: Build pushed to Nexus
        username: Concourse
        pipeline_name: spring-music
        pipeline_url:  {{nonprod_pipeline_url}}
        statuscolor: lime
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        flow_token: {{flow_token}}
  - put: snapshots
    params:
      file: build_output/spring-music-*.war
      version_file: version/version  
      
      
- name: deploy
  serial: true
  plan:
  - aggregate:
    - get: repo
      passed: [build]
    - get: snapshots
      passed: [build]
      trigger: true      

  - put: dev-cloud
    params:
      manifest: repo/manifest-ci.yml
      path: snapshots/spring-music*.jar
    on_success:
      put: flowdock-drone
      params:
        flow_token: {{flow_token}}
        message: New version in shared dev
        thread_title: Deployment
        msg_status_value: SUCCESS
        pipeline_name: spring-music
        pipeline_url: {{nonprod_pipeline_url}}
        msg_title: New cf push
        username: Concourse
        statuscolor: lime
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
    on_failure:
      put: flowdock-drone
      params:
        text: Deploy Failed
        thread_title: Deployment
        msg_status_value: FAIL
        msg_title: Deploy failure
        username: Concourse
        pipeline_name: spring-music
        pipeline_url:  {{nonprod_pipeline_url}}
        statuscolor: cyan
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        flow_token: {{flow_token}}
      
