---
platform: linux

image_resource:
  type: docker-image
  source: { respository: datianshi/gradle }


inputs:
  - name: music-repo
  - name: version

run:
  path: music-repo/ci/tasks/build-artifact.sh
