---
platform: linux

image_resource:
  type: docker-image
  source: { repository: datianshi/gradle }


inputs:
  - name: music-repo
  - name: version

outputs:
 - name: build_output

run:
  path: music-repo/ci/tasks/build-artifact.sh
